# Generated by Django 4.1.6 on 2023-02-01 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('type', models.CharField(choices=[('owner', 'owner'), ('operator', 'operator')], default='owner', max_length=20)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('area', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='img/plots/', verbose_name='Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.customer', verbose_name='owner')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('crop_type', models.CharField(choices=[('Tomatoes', 'Tomatoes'), ('Onions', 'Onions'), ('Cabbage', 'Cabbage'), ('Carrots', 'Carrots')], default='Cabbage', max_length=20)),
                ('month', models.CharField(choices=[('January', 'January'), ('Febuary', 'Febuary'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Feb', max_length=20)),
                ('income', models.PositiveIntegerField(default=0)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.customer', verbose_name='operator')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.plot', verbose_name='land')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
